spring:
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://localhost:3306/gulimall_pms
    url: jdbc:mysql://192.168.116.128:3306/gulimall_pms?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.116.128
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8990
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.atguigu.gulimall: debug

# 自定义线程池参数
gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300

cloud:
  aws:
    region:
      static: ca-central-1
    stack:
      auto: false
    credentials:
      profile-name: default